// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjne13Bw9rkfnOKsI1vx5d_qdgL4hOV7Y',
    appId: '1:694593299609:web:94161e12ae47feb3248408',
    messagingSenderId: '694593299609',
    projectId: 'finanseeup',
    authDomain: 'finanseeup.firebaseapp.com',
    storageBucket: 'finanseeup.appspot.com',
    measurementId: 'G-4T9CPH0S3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSTNFmLYLn99f5JKzXGgRVn7ONLZ1Q9Rs',
    appId: '1:694593299609:android:041089c25f0a00b4248408',
    messagingSenderId: '694593299609',
    projectId: 'finanseeup',
    storageBucket: 'finanseeup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB75tHcIE5L5_o9EsukkfC4Lmf2QZgE5Cw',
    appId: '1:694593299609:ios:40a11f62d4590e41248408',
    messagingSenderId: '694593299609',
    projectId: 'finanseeup',
    storageBucket: 'finanseeup.appspot.com',
    iosClientId: '694593299609-85t25q0h2h29bg4df9og8oj3sr6j3mmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finanseeup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB75tHcIE5L5_o9EsukkfC4Lmf2QZgE5Cw',
    appId: '1:694593299609:ios:7135b07e85093841248408',
    messagingSenderId: '694593299609',
    projectId: 'finanseeup',
    storageBucket: 'finanseeup.appspot.com',
    iosClientId: '694593299609-qkkmrlppgp2hqftm3qe26k8jis3ra4hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.finanseeup.RunnerTests',
  );
}
